// Code generated by protoc-gen-go.
// source: mvccpb.proto
// DO NOT EDIT!

/*
Package mvccpb is a generated protocol buffer package.

It is generated from these files:
	mvccpb.proto

It has these top-level messages:
	MetaItem
	MetaLock
	Meta
*/
package mvccpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MetaLockType int32

const (
	MetaLockType_ReadOnly  MetaLockType = 1
	MetaLockType_ReadWrite MetaLockType = 2
)

var MetaLockType_name = map[int32]string{
	1: "ReadOnly",
	2: "ReadWrite",
}
var MetaLockType_value = map[string]int32{
	"ReadOnly":  1,
	"ReadWrite": 2,
}

func (x MetaLockType) Enum() *MetaLockType {
	p := new(MetaLockType)
	*p = x
	return p
}
func (x MetaLockType) String() string {
	return proto.EnumName(MetaLockType_name, int32(x))
}
func (x *MetaLockType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetaLockType_value, data, "MetaLockType")
	if err != nil {
		return err
	}
	*x = MetaLockType(value)
	return nil
}
func (MetaLockType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MetaItem struct {
	StartTs          *uint64 `protobuf:"varint,1,opt,name=start_ts" json:"start_ts,omitempty"`
	CommitTs         *uint64 `protobuf:"varint,2,opt,name=commit_ts" json:"commit_ts,omitempty"`
	IsPk             *bool   `protobuf:"varint,3,opt,name=is_pk" json:"is_pk,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MetaItem) Reset()                    { *m = MetaItem{} }
func (m *MetaItem) String() string            { return proto.CompactTextString(m) }
func (*MetaItem) ProtoMessage()               {}
func (*MetaItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MetaItem) GetStartTs() uint64 {
	if m != nil && m.StartTs != nil {
		return *m.StartTs
	}
	return 0
}

func (m *MetaItem) GetCommitTs() uint64 {
	if m != nil && m.CommitTs != nil {
		return *m.CommitTs
	}
	return 0
}

func (m *MetaItem) GetIsPk() bool {
	if m != nil && m.IsPk != nil {
		return *m.IsPk
	}
	return false
}

type MetaLock struct {
	Type             *MetaLockType `protobuf:"varint,1,opt,name=type,enum=mvccpb.MetaLockType" json:"type,omitempty"`
	StartTs          *uint64       `protobuf:"varint,2,opt,name=start_ts" json:"start_ts,omitempty"`
	PrimaryKey       []byte        `protobuf:"bytes,3,opt,name=primary_key" json:"primary_key,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MetaLock) Reset()                    { *m = MetaLock{} }
func (m *MetaLock) String() string            { return proto.CompactTextString(m) }
func (*MetaLock) ProtoMessage()               {}
func (*MetaLock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MetaLock) GetType() MetaLockType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MetaLockType_ReadOnly
}

func (m *MetaLock) GetStartTs() uint64 {
	if m != nil && m.StartTs != nil {
		return *m.StartTs
	}
	return 0
}

func (m *MetaLock) GetPrimaryKey() []byte {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

// Meta will be splitted into a list if it gets too big.
// An auto increased index will be assigned to each Meta node. The field `next`
// stores next Meta's index and next is 0 if no more Meta exists.
// Meta0 always contains the Lock(if any) and the latest versions.
type Meta struct {
	Lock             *MetaLock   `protobuf:"bytes,1,opt,name=lock" json:"lock,omitempty"`
	Items            []*MetaItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Next             *uint64     `protobuf:"varint,3,opt,name=next" json:"next,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Meta) GetLock() *MetaLock {
	if m != nil {
		return m.Lock
	}
	return nil
}

func (m *Meta) GetItems() []*MetaItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Meta) GetNext() uint64 {
	if m != nil && m.Next != nil {
		return *m.Next
	}
	return 0
}

func init() {
	proto.RegisterType((*MetaItem)(nil), "mvccpb.MetaItem")
	proto.RegisterType((*MetaLock)(nil), "mvccpb.MetaLock")
	proto.RegisterType((*Meta)(nil), "mvccpb.Meta")
	proto.RegisterEnum("mvccpb.MetaLockType", MetaLockType_name, MetaLockType_value)
}

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xe9, 0x6e, 0x94, 0xec, 0x6c, 0x94, 0x18, 0x3d, 0xec, 0x49, 0xa5, 0x27, 0x51, 0xe8,
	0xa1, 0x3f, 0xc0, 0xbb, 0xa0, 0x08, 0xa2, 0x78, 0x2c, 0x31, 0xe6, 0x50, 0xda, 0x34, 0x21, 0x1d,
	0xc4, 0xfc, 0x7b, 0xa7, 0xa9, 0x7b, 0x68, 0x8f, 0x6f, 0x66, 0xde, 0x37, 0xef, 0x81, 0x70, 0x3f,
	0xc6, 0x84, 0xaf, 0x2a, 0x44, 0x8f, 0x5e, 0x9d, 0xce, 0xaa, 0x7c, 0x04, 0xfe, 0x62, 0x51, 0x3f,
	0xa1, 0x75, 0x4a, 0x02, 0x1f, 0x51, 0x47, 0x6c, 0x70, 0x3c, 0x14, 0xb7, 0xc5, 0x1d, 0x53, 0x17,
	0xb0, 0x33, 0xde, 0xb9, 0x36, 0x8f, 0x36, 0x79, 0x74, 0x06, 0x27, 0xed, 0xd8, 0x84, 0xee, 0xb0,
	0x25, 0xc9, 0xcb, 0x8f, 0xd9, 0xff, 0xec, 0x4d, 0xa7, 0x4a, 0x60, 0x98, 0x82, 0xcd, 0xde, 0xf3,
	0xfa, 0xaa, 0xfa, 0x7f, 0x78, 0xdc, 0xbf, 0xd3, 0x6e, 0xf1, 0x63, 0x06, 0x5e, 0xc2, 0x3e, 0xc4,
	0xd6, 0xe9, 0x98, 0x9a, 0xce, 0xa6, 0x8c, 0x15, 0x84, 0x65, 0x93, 0x4d, 0x5d, 0x03, 0xeb, 0xc9,
	0x9a, 0x91, 0xfb, 0x5a, 0xae, 0x91, 0xea, 0x86, 0xd2, 0x50, 0xf4, 0x89, 0xb5, 0x5d, 0x1f, 0xe4,
	0x4e, 0x02, 0xd8, 0x60, 0x7f, 0x31, 0x63, 0xd9, 0xfd, 0x03, 0x88, 0x45, 0x1a, 0x01, 0xfc, 0xcd,
	0xea, 0xef, 0xd7, 0xa1, 0x4f, 0xb2, 0xa0, 0x6a, 0xbb, 0x49, 0x7d, 0x46, 0x42, 0xca, 0xcd, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x9d, 0x16, 0x11, 0x31, 0x01, 0x00, 0x00,
}
